name: "Setup Flutter from submodule"
description: "Setup Flutter and caches"

runs:
  using: "composite"
  steps:
    - name: Set Flutter paths
      shell: bash
      run: |
        WORKSPACE='${{ github.workspace }}'
        if [ "${{ runner.os }}" == "Windows" ]; then
          WORKSPACE=$(cygpath -m '${{ github.workspace }}') # Replace backslashes with forward slashes
        fi
        echo "FLUTTER_ROOT=${WORKSPACE}/submodules/flutter" >> $GITHUB_ENV
        echo "PUB_CACHE=${WORKSPACE}/submodules/flutter/.pub-cache" >> $GITHUB_ENV
        echo "${{ env.FLUTTER_ROOT }}/bin" >> $GITHUB_PATH
        echo "${{ env.PUB_CACHE }}/bin" >> $GITHUB_PATH

    - name: Process Flutter version
      shell: bash
      run: |
        # Copy .flutter.version.json to flutter/bin/cache
        mkdir -p submodules/flutter/bin/cache/
        cp submodules/.flutter.version.json submodules/flutter/bin/cache/flutter.version.json

        # Extract info from .flutter.version.json
        FLUTTER_VERSION=$(grep flutterVersion submodules/.flutter.version.json | cut -d'"' -f4)
        FLUTTER_CHANNEL=$(grep channel submodules/.flutter.version.json | cut -d'"' -f4)
        echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV
        echo "FLUTTER_CHANNEL=$FLUTTER_CHANNEL" >> $GITHUB_ENV

        # Flutter version hash for caching
        FLUTTER_HASH="${FLUTTER_CHANNEL}-${FLUTTER_VERSION}-${{ hashFiles('submodules/flutter/bin/internal/*.version') }}"
        echo "FLUTTER_HASH=$FLUTTER_HASH" >> $GITHUB_ENV

        echo "Using Flutter version ${FLUTTER_VERSION} on channel ${FLUTTER_CHANNEL}, hash ${FLUTTER_HASH}"

    - name: Cache Flutter
      id: cache-flutter
      uses: actions/cache@v4
      with:
        path: |
          submodules/flutter/**/.dart_tool/
          submodules/flutter/bin/cache/
          submodules/flutter/packages/flutter_tools/
        key: ${{ runner.os }}-${{ runner.arch }}-flutter-${{ env.FLUTTER_HASH }}

    - name: Cache Pub
      id: cache-pub
      uses: actions/cache@v4
      with:
        path: submodules/flutter/.pub-cache
        key: ${{ runner.os }}-${{ runner.arch }}-pub-${{ env.FLUTTER_HASH }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-pub-${{ env.FLUTTER_HASH }}-

    # Flutter relies on git to identify its own version.
    # We use a shallow clone for speed which doesn't include tags, so manually set them here.
    - name: Restore Flutter version information
      shell: bash
      run: |
        # Set branch unconditionally
        git checkout -B "$FLUTTER_CHANNEL"

        # Tag the current commit
        git -C submodules/flutter tag -f "$FLUTTER_CHANNEL"
        git -C submodules/flutter tag -f "$FLUTTER_VERSION"

    - name: Run flutter doctor
      shell: bash
      run: flutter doctor
