name: "Setup Flutter from submodule"
description: "Setup Flutter and caches"

runs:
  using: "composite"
  steps:
    - name: Add env variables
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          WORKSPACE=$(cygpath -m '${{ github.workspace }}')
        else
          WORKSPACE='${{ github.workspace }}'
        fi
        echo "FLUTTER_ROOT=${WORKSPACE}/submodules/flutter" >> $GITHUB_ENV
        echo "PUB_CACHE=${WORKSPACE}/submodules/flutter/.pub-cache" >> $GITHUB_ENV
        ENGINE_VERSION=$(cat ${WORKSPACE}/submodules/flutter/bin/internal/engine.version)
        FLUTTER_PACKAGES_VERSION=$(cat ${WORKSPACE}/submodules/flutter/bin/internal/flutter_packages.version)
        echo "FLUTTER_HASH=${ENGINE_VERSION}-${FLUTTER_PACKAGES_VERSION}" >> $GITHUB_ENV

    - name: Add Flutter to PATH
      shell: bash
      run: |
        echo "${{ env.FLUTTER_ROOT }}/bin" >> $GITHUB_PATH
        echo "${{ env.PUB_CACHE }}/bin" >> $GITHUB_PATH

    - name: Cache Flutter
      id: cache-flutter
      uses: actions/cache@v4
      with:
        path: |
          submodules/flutter/**/.dart_tool/
          submodules/flutter/bin/cache/
          submodules/flutter/packages/flutter_tools/
        key: ${{ runner.os }}-${{ runner.arch }}-flutter-${{ env.FLUTTER_HASH }}

    - name: Cache Pub
      id: cache-pub
      uses: actions/cache@v4
      with:
        path: submodules/flutter/.pub-cache
        key: ${{ runner.os }}-${{ runner.arch }}-pub-${{ env.FLUTTER_HASH }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-pub-${{ env.FLUTTER_HASH }}-

    # Flutter relies on tags to identify its own version.
    # We use a shallow clone for speed which doesn't include tags, so manually set them here.
    - name: Restore Flutter version information
      shell: bash
      run: |
        # Copy flutter.version.json
        mkdir -p submodules/flutter/bin/cache/
        cp submodules/.flutter.version.json submodules/flutter/bin/cache/flutter.version.json

        # Extract info
        FLUTTER_VERSION=$(grep flutterVersion submodules/.flutter.version.json | cut -d'"' -f4)
        FLUTTER_CHANNEL=$(grep channel submodules/.flutter.version.json | cut -d'"' -f4)
        echo "Found FLUTTER_VERSION=$FLUTTER_VERSION, FLUTTER_CHANNEL=$FLUTTER_CHANNEL"
        echo "$FLUTTER_VERSION" > submodules/flutter/version

        # Tag the current commit
        git -C submodules/flutter tag -f "$FLUTTER_CHANNEL"
        git -C submodules/flutter tag -f "$FLUTTER_VERSION"

        # Set branch
        git checkout -B "$FLUTTER_CHANNEL"

    - name: Run flutter doctor
      shell: bash
      run: flutter doctor
